name: Homelab CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, homelab]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Push with UV
        run: |
          # Use BuildKit for the cache mounts to work
          export DOCKER_BUILDKIT=1
          docker build -t 192.168.1.38:5000/my-python-app:latest .
          docker push 192.168.1.38:5000/my-python-app:latest

      - name: Deploy
        run: |
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 8080:8080 --restart always 192.168.1.38:5000/my-python-app:latest